openapi: 3.1.0
x-stoplight:
  id: 7827mmvuj68qh
info:
  title: User Authentication API
  version: '1.0'
  summary: User Authentication and Authorization API
  description: 'This API facilitates user authentication and authorization processes efficiently, offering functionalities for user creation, retrieval, and updates while ensuring security.'
  contact:
    name: Dale-Kurt Murray
    url: 'https://www.lunarops.io'
    email: dalekurt@lunarops.io
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/license/LICENSE-2.0.html'
servers:
  - url: 'http://localhost:8000'
paths:
  '/admin/users/{userid}':
    parameters:
      - schema:
          type: string
        name: userid
        in: path
        required: true
        description: The unique identifier of the user.
      - schema:
          type: string
        name: mobile
        in: query
        description: Filter users by their mobile number.
      - schema:
          type: string
        name: email
        in: query
        description: Filter users by their email address.
    get:
      summary: Retrieve User Information
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Jane Smith:
                  value:
                    id: 136
                    first_name: Jane
                    last_name: Smith
                    email: jane.smith@gmail.com
                    mobile: 347-123-4567
                    username: janesmith
                    password: s3cretPwd
                    email_verified: true
                    is_active: true
                    created_at: '2023-09-15 00:00:00'
                    updated_at: '2023-09-15 00:00:00'
                    last_login: '2023-09-15 00:00:00'
                Get User John Doe:
                  value:
                    id: 137
                    first_name: John
                    last_name: Doe
                    email: john.doe@gmail.com
                    mobile: 347-555-6789
                    username: johndoe
                    password: s3cret123
                    email_verified: true
                    is_active: true
                    created_at: '2023-09-14 00:00:00'
                    updated_at: '2023-09-14 00:00:00'
                    last_login: '2023-09-14 00:00:00'
        '404':
          description: User Not Found
      operationId: get-admin-users-userid
      description: 'Retrieve specific user details by their unique ID, mobile number, or email address.'
      x-stoplight:
        id: tx9pri7i92vd0
      tags:
        - admin
    patch:
      summary: Update User Information
      operationId: patch-admin-users-userid
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated First Name:
                  value:
                    id: 136
                    first_name: Updated Jane
                Updated Last Name:
                  value:
                    id: 136
                    last_name: Updated Smith
                Updated Email and Mobile:
                  value:
                    id: 136
                    email: updated.jane.smith@gmail.com
                    mobile: 347-123-9876
                Updated Password:
                  value:
                    id: 136
                    password: newSecretPwd
                Updated Activation Status:
                  value:
                    id: 136
                    is_active: false
                Combined Updates:
                  value:
                    id: 136
                    first_name: Combined
                    last_name: Updates
                    email: combined.updated@gmail.com
                    mobile: 347-987-1234
                    password: complexPassword
                    is_active: true
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: 'Modify user information, including first name, last name, email, mobile number, password, and activation status.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                  description: Providing a new email temporarily sets the email verification status to false.
                  format: email
                mobile:
                  type: string
                  description: Providing a new email temporarily sets the email verification status to false.
                password:
                  type: string
                  format: password
                is_active:
                  type: boolean
                  default: true
            examples:
              Update First Name:
                value:
                  first_name: Updated Jane
              Update Last Name:
                value:
                  last_name: Updated Smith
              Update Email and Mobile:
                value:
                  email: updated.jane.smith@gmail.com
                  mobile: 347-123-9876
              Update Password:
                value:
                  password: newSecretPwd
              Update Activation Status:
                value:
                  is_active: false
              Combined Updates:
                value:
                  first_name: Combined
                  last_name: Updates
                  email: combined.updated@gmail.com
                  mobile: 347-987-1234
                  password: complexPassword
                  is_active: true
      x-stoplight:
        id: a42zk931vnjdl
      tags:
        - admin
    delete:
      summary: Delete User
      operationId: delete-admin-users-userid
      responses:
        '200':
          description: OK
        '404':
          description: User Not Found
      description: Permanently remove an existing user and their associated data.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples:
              Delete User Example:
                value:
                  id: 136
                  first_name: Jane
                  last_name: Smith
                  email: jane.smith@gmail.com
                  mobile: 347-123-4567
                  username: janesmith
                  password: s3cretPwd
                  email_verified: true
                  is_active: true
      tags:
        - admin
  /admin/users:
    post:
      summary: Create New User
      operationId: post-admin-users
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    first_name: Bob
                    last_name: Fellow
                    email: bob.fellow@gmail.com
                    username: bobfellow
                    password: p@s$w0rd
                    mobile: 347-123-0001
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
          headers: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                Example 1:
                  first_name: David
                  last_name: Gavin
                  email: davidg@gmail.com
                  mobile: 347-123-4567
                  username: davidg
                  password: s3cr3tp@assw0rd
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                mobile:
                  type: string
                username:
                  type: string
                password:
                  type: string
                  format: password
            examples:
              Create User David Gavin:
                value:
                  first_name: David
                  last_name: Gavin
                  email: davidg@gmail.com
                  mobile: 347-123-4567
                  username: davidg
                  password: s3cr3tp@assw0rd
        description: Create a new user with the specified details.
      description: Add a new user
      x-stoplight:
        id: sjjnmow1fpaff
      tags:
        - admin
    parameters: []
    get:
      summary: Get All Users
      operationId: get-admin-users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      x-stoplight:
        id: h58p37bt8cvj6
      description: Retrieve a list of all users
      tags:
        - admin
  '/users/{userid}':
    parameters:
      - schema:
          type: string
        name: userid
        in: path
        required: true
        description: The unique identifier of the user.
    get:
      summary: Retrieve User Information
      tags:
        - users
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 134
                    first_name: Alice
                    last_name: Smith
                    email: alice.smith@gmail.com
                    mobile: 347-321-1234
                    username: alicesmith
                    password: s3rewtwsdf
                    email_verified: true
                    is_active: true
                    created_at: '2023-09-12 00:00:00'
                    updated_at: '2023-09-12 00:00:00'
                    last_login: '2023-09-12 00:00:00'
      operationId: get-users-userid
      description: Retrieve specific user details by their unique ID.
      x-stoplight:
        id: chqbkwzjtrmf3
    patch:
      summary: Update User Information
      operationId: patch-users-userid
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    first_name: Rebecca
                    last_name: Baker
                    email: rebecca@gmail.com
                    username: rebecca
                    password: p@s$w0rd
                    mobile: 347-876-5432
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: 'Modify user information, including first name, last name, email, mobile number, password, and activation status.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                  description: Providing a new email temporarily sets the email verification status to false.
                  format: email
                mobile:
                  type: string
                  description: Providing a new email temporarily sets the email verification status to false.
                password:
                  type: string
                  format: password
                is_active:
                  type: boolean
                  default: true
            examples:
              Update First Name:
                value:
                  first_name: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  last_name: Baker
                  mobile: 347-122-1209
              Update Password:
                value:
                  password: s3cr3tpaswword
        description: Customize user information according to your requirements.
      x-stoplight:
        id: 5m1t6akzcoqbq
      tags:
        - users
  /users:
    post:
      summary: Create New User
      operationId: post-users
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    first_name: Bob
                    last_name: Fellow
                    email: bob.fellow@gmail.com
                    username: bobfellow
                    password: p@s$w0rd
                    mobile: 347-123-0001
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
          headers: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                Example 1:
                  first_name: David
                  last_name: Gavin
                  email: davidg@gmail.com
                  mobile: 347-123-4567
                  username: davidg
                  password: s3cr3tp@assw0rd
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                mobile:
                  type: string
                username:
                  type: string
                password:
                  type: string
                  format: password
            examples:
              Create User David Gavin:
                value:
                  first_name: David
                  last_name: Gavin
                  email: davidg@gmail.com
                  mobile: 347-123-4567
                  username: davidg
                  password: s3cr3tp@assw0rd
        description: Create a new user with the specified details.
      description: Add a new user to your system effortlessly.
      x-stoplight:
        id: gk6p69nvj8e8s
      tags:
        - users
    parameters: []
components:
  schemas:
    User:
      type: object
      x-examples:
        Example 1:
          id: 0
          first_name: string
          last_name: string
          email: string
          mobile: string
          username: string
          password: string
          email_verified: true
          is_active: true
          created_at: string
          updated_at: string
          last_login: string
      title: User
      description: This schema represents user details within the system.
      examples:
        - id: 0
          first_name: string
          last_name: string
          email: string
          mobile: string
          username: string
          password: string
          email_verified: true
          is_active: true
          created_at: string
          updated_at: string
          last_login: string
      properties:
        id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
          format: email
        mobile:
          type: string
        username:
          type: string
        password:
          type: string
          format: password
        email_verified:
          type: boolean
        avatar:
          type: string
          x-stoplight:
            id: t981ej3f91c1b
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        last_login:
          type: string
          format: date-time
          example: '2023-09-13 00:00:00'
        is_admin:
          type: boolean
          x-stoplight:
            id: 9uw9d9l7r01sx
          default: false
        roles:
          type: array
          x-stoplight:
            id: 6v8vybuylwhoi
          items:
            x-stoplight:
              id: 1u4fl0pgx04ro
            type: string
            default: user
      required:
        - first_name
        - last_name
        - email
        - mobile
        - username
        - password
tags:
  - name: admin
    description: Access to user management as an admin
  - name: users
    description: Access to user management as a regular user
